[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[profile.default.fuzz]
runs = 1000
max_test_rejects = 100000

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false

# For coverage
[profile.coverage]
via_ir = true

# Gas reports
gas_reports = ["*"]